version: '3.7'

services:
  webapp:
    container_name: Bookshop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./static:/app/static
      - static-files:/static
    ports:
      - 8005:8000
    env_file:
      - .env
    networks:
      - bookshop_net
    restart: on-failure

volumes:
  static-files:
      name: bookshop_volume

networks:
  bookshop_net:
    external:
       name: supernet


