# Generated by Django 3.2 on 2021-12-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
