# Generated by Django 3.2 on 2021-12-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('HARDCOVER', 'Hard Cover'), ('PAPERBACK', 'Paper Back'), ('AUDIOBOOK', 'Audio Book')], max_length=20)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
    ]
