# Generated by Django 3.2 on 2021-12-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booktype'),
        ),
    ]
