# Generated by Django 3.2 on 2021-12-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_product', to='core.book'),
        ),
    ]
